### ISSUE TITLE
Cannot override property "javamelody.monitoringPath"

### ISSUE THREAD

**Issue by HaraldVogl** [Catalysts/cat-boot#4]
when I define the javamelody.monitoringPath in my application.properties it is ignored

the setMonitoringPath() method in JavaMelodyAutoConfiguration is never called

when I have time I will fix it and provide an MR

**Comment by NoUsername** [comment]
i can confirm this. It seems the `@ConfigurationProperties` is used wrong. There should either be a separate bean which just consumes the config properties which then gets injected into the autoconfiguration class or sth like this: `@EnableConfigurationProperties(ConnectionSettings.class)`  https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties

**Comment by klu2** [comment]
https://github.com/Catalysts/cat-boot/commit/fbd9ab25f3e545b6210475d1a1e1a145a5efafdf
